grpc:
  server:
    port: 8044

server:
  port: 4044

jwt:
  private-key: ${JWT_PRIVATE_KEY:NOT_SET}
  public-key: ${JWT_PUBLIC_KEY:NOT_SET}

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:h2:mem:test_db # jdbc:postgresql://localhost:5432/tenant_service_db
    username: sa # postgres
    password:
    driver-class-name: org.h2.Driver # org.postgresql.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect # org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop # 'create-drop' or 'update' for dev, 'validate' or 'none' for production

