grpc:
  server:
    port: 8043

server:
  port: 4043

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE


spring:
  application:
    name=tenant-service

  datasource:
    url: jdbc:postgresql://localhost:5432/tenant_service_db
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # 'create-drop' or 'update' for dev, 'validate' or 'none' for production

    #properties:
      #javax.persistence.schema-generation.create-source: metadata
      #javax.persistence.schema-generation.scripts.action: create
      #javax.persistence.schema-generation.scripts.create-target: create.sql

  flyway:
    enabled: false

