package com.ams.appointment_service.model.constant;

public enum EventType {
    APPOINTMENT_BOOKED,
    APPOINTMENT_BOOKING_CONFIRM,

    APPOINTMENT_CANCELED_BY_STAFF,
    APPOINTMENT_CANCELED_BY_CUSTOMER,

    APPOINTMENT_RESCHEDULED_BY_STAFF,
    APPOINTMENT_RESCHEDULED_BY_CUSTOMER,
    APPOINTMENT_RESCHEDULED_CONFIRMED_BY_STAFF,
    APPOINTMENT_RESCHEDULED_CONFIRMED_BY_CUSTOMER,
}
